---
- hosts: dnsservers
  vars_files:
    - "group_vars/os_{{ ansible_distribution }}.yml"
    - "group_vars/env_{{ env }}.yml"
    - "host_vars/{{ ansible_hostname }}.yml"
  roles:
    - nsd
    - pf
