---
- hosts: all
  vars_files:
    - "group_vars/os_{{ ansible_distribution }}.yml"
    - "group_vars/env_{{ env }}.yml"
    - "host_vars/{{ ansible_hostname }}.yml"
  roles:
    - common
    - doas
    - aliases

- include: dnsservers.yml
- include: smtpservers.yml
