---
  - name: Create config file
    become: yes
    template:
      src: smtpd.conf.j2
      dest: /etc/mail/smtpd.conf
      owner: root
      group: "{{ smtpd_group }}"
      mode: 0640
      validate: smtpd -n -f %s
    notify:
     - restart smtpd

  - name: Enable OpenSMTPD on boot and start it
    become: yes
    service:
      name: smtpd
      state: started
      enabled: yes
