---
  - name: Forward root mail to admin email
    become: yes
    lineinfile:
      dest: /etc/mail/aliases
      line: "root: {{root_aliases}}"
      regexp: '^'
      state: present
      insertafter: EOF
    when: root_aliases is defined
    notify:
     - restart smtpd
