---
  - name: Configure ntpd
    become: yes
    template:
      src: ntpd.conf.j2
      owner: root
      group: "{{ ntp_group }}"
      mode: 0640
      dest: /etc/ntpd.conf
    notify:
      - restart ntpd

  - name: Ensure ntpd is running and enabled
    become: yes
    service:
      name: ntpd
      state: started
      enabled: yes
