---
  - name: Install unzip
    become: yes
    openbsd_pkg:
      name: unzip-6.0p9
      state: present

  - name: Install php-curl
    become: yes
    openbsd_pkg:
      name: php-curl-5.6.23p0
      state: present

  - name: Enable php-curl
    become: yes
    file:
      src: /etc/php-5.6.sample/curl.ini
      dest: /etc/php-5.6/curl.ini
      state: link

  - name: Create rainloop www directory
    become: yes
    file:
      dest: /var/www/htdocs/rainloop/
      owner: www
      group: www
      mode: 0755
      state: directory

  - name: Create etc directory in rainloop chroot
    become: yes
    file:
      dest: /var/www/etc
      state: directory

  - name: Copy resolv.conf in rainloop chroot
    become: yes
    copy:
      src: /etc/resolv.conf
      dest: /var/www/etc
      remote_src: yes

  - name: Unarchive rainloop
    become: yes
    unarchive:
      #src: http://repository.rainloop.net/v2/webmail/rainloop-community-latest.zip
      #remote_src: yes
      src: files/rainloop.zip
      dest: /var/www/htdocs/rainloop
      owner: www
      group: www

  - name: Fix rainloop directory chmod
    become: yes
    command: find /var/www/htdocs/rainloop -type d -exec chmod 755 {} \;

  - name: Fix rainloop files chmod
    become: yes
    command: find /var/www/htdocs/rainloop -type f -exec chmod 644 {} \;

  - name: Register php-fpm pool
    set_fact:
      php_fpm_pool: "{{ php_fpm_pool | default([]) | union(['rainloop']) }}"

  - name: Generate httpd config
    set_fact:
      rainloop_httpd_conf:
        name: webmail.{{ root_domain }}
        tls_only: yes
        locations:
          - path: /data*
            block: yes
          - path: /rainloop*
            root:
              directory: /htdocs/rainloop/rainloop
              strip: 1
          - path: /*
            root:
              directory: /htdocs/rainloop/index.php
            fastcgi:
              socket: /run/rainloop.sock

  - name: Register httpd server
    set_fact:
      httpd_servers: "{{ httpd_servers | default([]) | union([rainloop_httpd_conf]) }}"
