---
  - name: Configure httpd
    become: yes
    template:
      src: httpd.conf.j2
      dest: /etc/httpd.conf
      owner: root
      group: wheel
      mode: 0600
    notify:
     - restart httpd

  - name: Enable httpd on boot and start it
    become: yes
    service:
      name: httpd
      state: started
      enabled: yes
