---
  - name: OpenBSD | Adjust installpath in /etc/pkg.conf
    become: yes
    when: ansible_distribution == "OpenBSD"
    lineinfile:
      dest: /etc/pkg.conf
      line: "installpath = http://{{openbsd_mirror}}/pub/OpenBSD/%c/packages/%a/"
      regexp: '^'
      state: present
      insertafter: EOF
      create: yes

  - include: ntp.yml
  - include: users.yml
