---
- name: OpenBSD | Adjust installpath in /etc/pkg.conf
  become: yes
  become_method: doas
  when: ansible_distribution == "OpenBSD"
  lineinfile:
    dest=/etc/pkg.conf
    backup=yes
    line="installpath = http://{{openbsd_mirror}}/pub/OpenBSD/{{ansible_distribution_release}}/packages/{{ansible_machine}}/"
    regexp='^'
    state=present
    insertafter=EOF
    create=yes
