---
    - name: Create admin users
      become: yes
      user:
        name: "{{ item.name }}"
        append: yes
        groups: "wheel"
        home: "/home/{{ item.name }}/"
        system: no
        shell: /bin/sh
      when: item.admin is defined and item.admin
      with_items: "{{ users }}"

    - name: Create .ssh directory
      become: yes
      file:
        dest: "/home/{{ item.name }}/.ssh"
        mode: 0700
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        state: directory
      when: item.ssh_key is defined
      with_items: "{{ users }}"

    - name: Add ssh public key to authorized_keys
      become: yes
      copy:
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        content: "{{ item.ssh_key }}"
        mode: 0600
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      when: item.ssh_key is defined
      with_items: "{{ users }}"
