---
  - name: Install php-fpm
    become: yes
    openbsd_pkg:
      name: php-5.6.23p0
      state: present

  - name: Create php-fpm config directory
    become: yes
    file:
      dest: "/etc/fpm.d"
      mode: 0700
      owner: root
      group: wheel
      state: directory

  - name: Create php-fpm pool
    become: yes
    template:
      src: pool.conf.j2
      dest: "/etc/fpm.d/{{ item }}.conf"
      owner: root
      group: wheel
      mode: 0600
    with_items: "{{ php_fpm_pool | default([]) }}"
    notify:
     - restart php-fpm

  - name: Configure php-fpm
    become: yes
    template:
      src: php-fpm.conf.j2
      dest: /etc/php-fpm.conf
      owner: root
      group: wheel
      mode: 0600
    notify:
     - restart php-fpm
