---
  - name: Install baikal
    become: yes
    openbsd_pkg:
      name: baikal-0.2.7p2
      state: present

  - name: Register php-fpm pool
    set_fact:
      php_fpm_pool: "{{ php_fpm_pool | default([]) | union(['baikal']) }}"

  - name: Generate httpd config
    set_fact:
      baikal_httpd_conf:
        name: dav.{{ root_domain }}
        tls_only: yes
        locations:
          - path: /.well-known/carddav*
            root:
              directory: /baikal/html/card.php
            fastcgi:
              socket: /run/baikal.sock
          - path: /.well-known/caldav*
            root:
              directory: /baikal/html/cal.php
            fastcgi:
              socket: /run/baikal.sock

  - name: Register httpd server
    set_fact:
      httpd_servers: "{{ httpd_servers | default([]) | union([baikal_httpd_conf]) }}"
