---
  - name: Install openvpn
    become: yes
    openbsd_pkg:
      name: openvpn
      state: present

  - name: Create openvpn config directory
    become: yes
    file:
      dest: "{{ openvpn_configdir }}"
      mode: 0750
      owner: root
      group: wheel
      state: directory

  - name: Create openvpn keys directory
    become: yes
    file:
      dest: "{{ openvpn_configdir }}/keys"
      mode: 0750
      owner: root
      group: wheel
      state: directory

  - name: Configure openvpn
    become: yes
    template:
      src: server.conf.j2
      dest: /etc/openvpn/server.conf
      owner: root
      group: wheel
      mode: 0640
    notify:
      - restart openvpn

  - name: Install ca
    become: yes
    copy:
      dest: "{{ openvpn_configdir }}/keys/ca.crt"
      content: "{{ openvpn_ca }}"
      mode: 0640
      owner: root
      group: wheel
    notify:
     - restart openvpn

  - name: Install cert
    become: yes
    copy:
      dest: "{{ openvpn_configdir }}/keys/server.crt"
      content: "{{ openvpn_cert }}"
      mode: 0640
      owner: root
      group: wheel
    notify:
     - restart openvpn

  - name: Install key
    become: yes
    copy:
      dest: "{{ openvpn_configdir }}/keys/server.key"
      content: "{{ openvpn_key }}"
      mode: 0600
      owner: root
      group: wheel
    notify:
     - restart openvpn

  - name: Install dh
    become: yes
    copy:
      dest: "{{ openvpn_configdir }}/keys/server.dh"
      content: "{{ openvpn_dh }}"
      mode: 0640
      owner: root
      group: wheel
      validate: openssl dhparam -in %s -check -text -noout
    notify:
     - restart openvpn

  - name: Install ta
    become: yes
    copy:
      dest: "{{ openvpn_configdir }}/keys/ta.key"
      content: "{{ openvpn_ta }}"
      mode: 0600
      owner: root
      group: wheel
    notify:
     - restart openvpn

  - name: Configure interface
    become: yes
    template:
      src: hostname.j2
      dest: "/etc/hostname.{{ openvpn_dev }}0"
      owner: root
      group: wheel
      mode: 0640
    notify:
      - restart openvpn

  - name: Enable IPv4 Forwarding
    become: yes
    sysctl:
      name: net.inet.ip.forwarding
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
